@MsSentinel.ObservabilityDemo.DataCollectionRule_HostAddress = http://localhost:5048

GET {{MsSentinel.ObservabilityDemo.DataCollectionRule_HostAddress}}/weatherforecast/
Accept: application/json

###
